2013-06-08 :
CREATE TABLE  `job_db`.`article_status` ( `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY , `nama` VARCHAR( 200 ) NOT NULL ) ENGINE = MYISAM ;

2013-06-10 :
CREATE TABLE `job_db`.`editor` ( `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY , `nama` VARCHAR( 255 ) NOT NULL , `email` VARCHAR( 255 ) NOT NULL , `passwd` VARCHAR( 255 ) NOT NULL ) ENGINE = MYISAM ;

